services:
  - type: web
    name: autocaptionfinal
    runtime: docker
    plan: free
    envVars:
      - key: WHISPER_DEVICE
        value: cpu
      - key: WHISPER_COMPUTE_TYPE
        value: int8
      - key: WHISPER_MODEL
        value: base
      - key: WHISPER_BEAM_SIZE
        value: "2"
      - key: WHISPER_BEST_OF
        value: "1"
      - key: WHISPER_THREADS
        value: "4"
